title: "tochisuke docs"
description: "技術ブログ - 学習と積み上げの記録"
baseurl: ""
url: "https://tochisuke221.github.io"

markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-optional-front-matter

relative_links:
  enabled: true
  collections: false

exclude:
  - CLAUDE.md