title: "tochisuke docs"
description: "技術ブログ - 学習と積み上げの記録"
baseurl: ""
url: "https://tochisuke221.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

relative_links:
  enabled: true
  collections: false

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

exclude:
  - CLAUDE.md